apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: host-device-ric
spec:
config: '{
    "cniVersion": "0.3.0",
    "type": "host-device",
    "device": "enp5s0",
    "ipam": {
    "type": "host-local",
    "subnet": "192.168.99.0/24",
    "rangeStart": "192.168.99.10",
    "rangeEnd": "192.168.99.10",
    "routes": [{
        "dst": "0.0.0.0/0"
    }],
    "gateway": "192.168.99.1"
    }
}'
